name: Suwokono CI (Python + Node)
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
        type: string
  push:
      branches: [ "main", "develop", "feature/*" ]
  pull_request:
      branches: [ "main", "develop", "feature/*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # # --------------------
      # # Build Suwokono Backend
      # # --------------------
      # - name: Build Suwokono Backend
      #   run: |
      #     docker build -t 534931273/suwokono-backend:v1.0.0 ./backend

      # # --------------------
      # # Build Suwokono Frontend
      # # --------------------
      # - name: Build Suwokono Frontend
      #   run: |
      #     docker build -t 534931273/suwokono-frontend:v1.0.0 ./frontend
      

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and Push Suwokono Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/suwokono-backend:v1.0.0
            ${{ secrets.DOCKERHUB_USERNAME }}/suwokono-backend:${{ github.sha }}


      - name: Build and Push Suwokono Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/suwokono-frontend:v1.0.0
            ${{ secrets.DOCKERHUB_USERNAME }}/suwokono-frontend:${{ github.sha }}
